FROM python:3.6.4-slim
MAINTAINER Rémy Greinhofer <remy.greinhofer@gmail.com>

# Create the directory containing the code.
RUN mkdir -p /code /requirements
WORKDIR /code

# Update the package list.
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    git \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Copy the requirements files.
COPY requirements.txt /requirements/

# Upgrade pip.
RUN pip install -r /requirements/requirements.txt tox==2.9.1

# Copy django entry point.
COPY docker/api/django-entrypoint.sh /

# Create unprivileged user for celery.
# RUN adduser --disabled-password --gecos '' celery

# Copy celery worker entry point.
# COPY docker/api/celery-entrypoint.sh /

CMD ["/django-entrypoint.sh"]
