postgresql:
  enabled: false
  imageTag: 10.1-alpine
  postgresPassword: postgres
  persistence:
    enabled: false
rabbitmq:
  enabled: false
  image: "rabbitmq:3.6.14-management-alpine"
  rabbitmqUsername: guest
  rabbitmqPassword: guest
  persistence:
    enabled: false
redis:
  enabled: false
  image: "redis:4.0.6-alpine"
  usePassword: false
  persistence:
    enabled: false
