ingress:
  hosts:
    - api.192.168.99.100.nip.io

persistence:
  enabled: false

service:
  type: NodePort

configmap:
  DJANGO_ALLOWED_HOSTS: api.192.168.99.100.nip.io
  DJANGO_CORS_ORIGIN_WHITELIST: www.192.168.99.100.nip.io
  DJANGO_SETTINGS_MODULE: api.settings.local
  RYR_API_API_OPTS: "--reload --timeout 1800 --chdir /usr/src/app"
